Repository vaticle/typedb-driver-python, pull requests merged in 2019-09, with the labels that each got.

#61 Use correct variable name in sync-dependencies-release
  .circleci/config.yml
Labels: bug, build

#62 Add title to GitHub Release
  BUILD
Labels: build, feature

#63 Adapt to latest @graknlabs_bazel_distribution
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
Labels: build

#64 Use release-validate-deps to ensure that client-python depends on a released version of protocol
  .circleci/config.yml
Labels: build

#65 Fix CI config
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
Labels: bug, build

#66 Fix CI by using Python 2 to run tests
  .circleci/config.yml
  BUILD
Labels: bug, build
