Repository vaticle/typedb-driver-python, pull requests merged in 2019-08, with the labels that each got.

#57 Update License to 2019
  .circleci/config.yml
  BUILD
  LICENSE
  WORKSPACE
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/dependencies.bzl
  deployment.properties
Labels: refactor

#59 Add codeowners
  .github/CODEOWNERS
Labels: feature

#60 Supply authentication credentials for keyspace operations
  dependencies/graknlabs/dependencies.bzl
  grakn/client.py
  grakn/service/Keyspace/KeyspaceService.py
Labels: feature, refactor
