Repository vaticle/typedb-driver-python, pull requests merged in 2019-03, with the labels that each got.

#19 Add grabl-marker for autoupdating
  WORKSPACE
Labels: build

#20 Deployment in CI pipeline
  .circleci/config.yml
  WORKSPACE
Labels: build

#21 Update usage of CI scripts
  .circleci/config.yml
  WORKSPACE
Labels: build

#22 Added WORKSPACE name
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
  WORKSPACE
Labels: build

#23 Fix CI by including @bazel_toolchains
  WORKSPACE
Labels: bug, build

#24 add dependency update to client-python ci workflow
  .circleci/config.yml
Labels: feature

#26 Fix dependency on enum34
  BUILD
  requirements.txt
Labels: bug, build

#27 Clear keyspace before tests
  tests/integration/test_grakn.py
Labels: bug

#25 removes the test-repo-deploy job from workflow
  .circleci/config.yml
Labels: refactor

#28 Grakn 1.5 synchronization
  .gitignore
  grakn/__init__.py
  grakn/service/Keyspace/KeyspaceService.py
  tests/integration/base.py
  tests/integration/test_concept.py
  tests/integration/test_grakn.py
  tests/integration/test_keyspace.py
Labels: feature, refactor

#29 Change python release and synchrnoize docs dependencies from grabl to…
  .circleci/config.yml
  WORKSPACE
Labels: bug

#32 Deployment tests
  .circleci/config.yml
  tests/deployment/requirements.txt
  tests/deployment/test.py
  tests/integration/test_grakn.py
Labels: feature

#33 Change class structure
  BUILD
  grakn/BUILD
  grakn/__init__.py
  grakn/client.py
  tests/deployment/test.py
  tests/integration/test_concept.py
  tests/integration/test_grakn.py
  tests/integration/test_keyspace.py
  tests/notes.md
Labels: refactor

#34 Rename grakn-core-all-linux.tar.gz
  .circleci/config.yml
Labels: bug, build

#35 Add benchmark as transitive dependency
  .circleci/config.yml
  WORKSPACE
Labels: bug

#37 Adapt to newest naming scheme
  .circleci/config.yml
Labels: build

#38 Python Open Request better error message
  grakn/client.py
Labels: refactor
