Repository vaticle/typedb-driver-python, pull requests merged in 2020-05, with the labels that each got.

#93 Add async iteration
  grakn/client.py
  grakn/service/Session/TransactionService.py
  grakn/service/Session/util/Communicator.py
  tests/integration/test_grakn.py
Labels: priority: high, type: feature, type: refactor

#91 Relax strict dependencies on external packages
  .circleci/config.yml
  BUILD
  requirements.txt
Labels: priority: high, type: build

#97 Don't use Python 2 in deploy-github
  .circleci/config.yml
Labels: priority: blocker, type: build

#98 Fix CI
  .circleci/config.yml
Labels: priority: blocker, type: build

#99 Fix queries larger than 50
  grakn/service/Session/util/RequestBuilder.py
  tests/integration/test_grakn.py
Labels: priority: blocker, type: bug

#102 Upgrade tests and build to Python 3
  .circleci/config.yml
  BUILD
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  requirements.txt
  tests/integration/base.py
Labels: type: build, type: refactor
