Repository vaticle/typedb-driver-python, pull requests merged in 2020-04, with the labels that each got.

#86 Upgrade to Bazel 3.0.0
  .bazelrc
  .bazelversion
  .circleci/config.yml
  BUILD
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  requirements.txt
  tests/integration/test_answer.py
  tests/integration/test_concept.py
Labels: priority: high, type: build

#87 Revert protocol to 1.0.4 and grakn to 1.6.2 for release
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
Labels: type: build

#85 Allow duplicate role players
  grakn/service/Session/Concept/Concept.py
  tests/integration/test_answer.py
  tests/integration/test_concept.py
Labels: priority: medium, type: refactor

#89 Remove python 2 compatibility import imap
  grakn/service/Session/Concept/RemoteConcept.py
  grakn/service/Session/TransactionService.py
  grakn/service/Session/util/ResponseReader.py
Labels: priority: high, type: bug
