Repository vaticle/typedb-driver-python, pull requests merged in 2020-06, with the labels that each got.

#104 Remove implicit, rename date to datetime, rename datatype to valuetype
  dependencies/graknlabs/dependencies.bzl
  grakn/client.py
  grakn/service/Session/Concept/Concept.py
  grakn/service/Session/Concept/RemoteConcept.py
  grakn/service/Session/TransactionService.py
  grakn/service/Session/util/RequestBuilder.py
  grakn/service/Session/util/ResponseReader.py
  grakn/service/Session/util/enums.py
  tests/deployment/test.py
  tests/integration/test_answer.py
  tests/integration/test_concept.py
  tests/integration/test_grakn.py
Labels: priority: high, type: refactor

#108 Add Explanation.get_rule()
  grakn/service/Session/util/ResponseReader.py
  tests/integration/test_answer.py
Labels: type: feature

#109 Add future-style get for explicit waiting and error handling
  grakn/service/Session/TransactionService.py
  grakn/service/Session/util/Communicator.py
  grakn/service/Session/util/ResponseReader.py
  tests/integration/test_grakn.py
Labels: priority: high, type: feature

#110 Update gRPC to 1.29.0
  dependencies/graknlabs/dependencies.bzl
  requirements.txt
Labels: priority: high

#112 Introduce further Query Options
  dependencies/graknlabs/dependencies.bzl
  grakn/client.py
  grakn/service/Session/TransactionService.py
  grakn/service/Session/util/RequestBuilder.py
  tests/integration/test_answer.py
  tests/integration/test_grakn.py
Labels: priority: high, type: refactor

#113 Update CI image to Ubuntu 16 and bump Build Tools
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build
