Repository vaticle/typedb-driver-python, pull requests merged in 2021-01, with the labels that each got.

#145 API cleanup: close on commit, isX methods
  grakn/concept/concept.py
  grakn/concept/thing/thing.py
  grakn/concept/type/relation_type.py
  grakn/concept/type/thing_type.py
  grakn/concept/type/type.py
  grakn/rpc/transaction.py
Labels: priority: medium, type: refactor

#144 Update usage of native_artifact_files
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
Labels: type: build, type: refactor

#146 Update grabl automation yaml syntax
  .grabl/automation.yml
Labels: type: build

#147 Delete query_pattern from ConceptMap
  grakn/concept/answer/concept_map.py
  grakn/concept/type/attribute_type.py
Labels: priority: medium, type: refactor

#149 Bump year in license headers to 2021
  LICENSE
  dependencies/graknlabs/repositories.bzl
Labels: type: build

#154 Update automation.yml to include `release` dependency for `common`
  .grabl/automation.yml
Labels: priority: high, type: feature

#155 Update automation.yml to include `behaviour` dependency
  .grabl/automation.yml
Labels: priority: high, type: bug

#156 BDD: Graql Steps
  grakn/client.py
  grakn/concept/concept.py
  grakn/concept/concept_manager.py
  grakn/concept/proto/concept_proto_builder.py
  grakn/concept/proto/concept_proto_reader.py
  grakn/concept/thing/attribute.py
  grakn/concept/thing/entity.py
  grakn/concept/thing/relation.py
  grakn/concept/type/value_type.py
  grakn/logic/logic_manager.py
  grakn/logic/rule.py
  grakn/options.py
  grakn/query/query_manager.py
  grakn/rpc/database_manager.py
  grakn/rpc/session.py
  grakn/rpc/transaction.py
  tests/behaviour/config/parameters.py
  tests/behaviour/context.py
  tests/behaviour/environment.py
  tests/behaviour/graql/graql_steps.py
  tests/behaviour/graql/language/define/BUILD
  tests/behaviour/graql/language/delete/BUILD
  tests/behaviour/graql/language/get/BUILD
  tests/behaviour/graql/language/insert/BUILD
  tests/behaviour/graql/language/match/BUILD
  tests/behaviour/graql/language/undefine/BUILD
  tests/integration/base.py
Labels: priority: medium, type: build

#157 Add BDD to CI and create pip deployment test
  .bazelrc
  .grabl/automation.yml
  BUILD
  WORKSPACE
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  grakn/concept/proto/concept_proto_builder.py
  tests/BUILD
  tests/behaviour/concept/thing/attribute/BUILD
  tests/behaviour/concept/thing/entity/BUILD
  tests/behaviour/concept/thing/relation/BUILD
  tests/behaviour/concept/type/attributetype/BUILD
  tests/behaviour/concept/type/entitytype/BUILD
  tests/behaviour/concept/type/relationtype/BUILD
  tests/behaviour/concept/type/thingtype/BUILD
  tests/behaviour/connection/database/BUILD
  tests/behaviour/connection/session/BUILD
  tests/behaviour/connection/transaction/BUILD
  tests/behaviour/graql/language/define/BUILD
  tests/behaviour/graql/language/delete/BUILD
  tests/behaviour/graql/language/get/BUILD
  tests/behaviour/graql/language/insert/BUILD
  tests/behaviour/graql/language/match/BUILD
  tests/behaviour/graql/language/undefine/BUILD
  tests/deployment/requirements.txt
  tests/deployment/test.py
  tests/integration/base.py
  tests/integration/test_concept.py
  tests/integration/test_connection.py
  tests/integration/test_query.py
  tools/behave_rule.bzl
Labels: priority: high, type: feature

#160 Update dependency on grakn-protocol
  BUILD
  requirements.txt
  requirements_dev.txt
Labels: priority: high, type: build, type: refactor

#163 Fix console warnings caused by out of date dependency
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  requirements.txt
  requirements_dev.txt
Labels: type: bug

#162 Remove dependency on six library
  BUILD
  grakn/rpc/stream.py
  grakn/rpc/transaction.py
  requirements.txt
  requirements_dev.txt
Labels: priority: high, type: refactor

#161 Add ability to retrieve all rules
  BUILD
  grakn/logic/logic_manager.py
  requirements.txt
  requirements_dev.txt
Labels: priority: medium, type: feature

#164 Update dependencies and the version
  VERSION
  requirements.txt
  requirements_dev.txt
Labels: type: build

#165 Upgrade grpcio to 1.35.0
  requirements.txt
  requirements_dev.txt
Labels: priority: medium, type: build

#170 Session pulses reuse threads instead of constructing new ones
  BUILD
  grakn/rpc/session.py
Labels: priority: high, type: bug

#169 Make behaviour tests rerunnable on developer's machine
  tools/behave_rule.bzl
Labels: priority: high, type: bug, type: build

#168 Create one gRPC Channel per session and transaction
  grakn/client.py
  grakn/rpc/session.py
  grakn/rpc/transaction.py
  tests/BUILD
  tests/integration/test_concurrent.py
Labels: priority: high, type: bug

#167 Reenable remote build caching
  .bazelrc
  .grabl/automation.yml
Labels: type: build
