Repository vaticle/typedb-driver-python, pull requests merged in 2021-02, with the labels that each got.

#174 Make private concept API method public
  grakn/concept/concept_manager.py
Labels: type: bug

#175 Fix 5 second delay before programs using the client actually terminate
  BUILD
  grakn/rpc/session.py
Labels: priority: high, type: bug

#173 Improve Cluster failover algorithm and add a test for it
  .grabl/automation.yml
  dependencies/graknlabs/artifacts.bzl
  grakn/client.py
  grakn/grakn_proto_builder.py
  grakn/options.py
  grakn/rpc/cluster/database_manager.py
  grakn/rpc/cluster/session.py
  requirements.txt
  requirements_dev.txt
  tests/BUILD
  tests/integration/test_cluster_failover.py
  tests/integration/test_concurrent.py
  tools/cluster_test_rule.bzl
Labels: priority: medium, type: feature

#177 Support new graql update queries
  .grabl/automation.yml
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  grakn/query/query_manager.py
  tests/behaviour/background/environment_base.py
  tests/behaviour/concept/thing/relation/relation_steps.py
  tests/behaviour/graql/graql_steps.py
  tests/behaviour/graql/language/update/BUILD
  tools/cluster_test_rule.bzl
Labels: priority: high, type: feature

#178 Make DatabaseManager more fault tolerant in Cluster
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  grakn/client.py
  grakn/rpc/cluster/database_manager.py
  tests/behaviour/background/cluster/environment.py
  tests/behaviour/background/core/environment.py
  tests/behaviour/background/environment_base.py
  tests/integration/test_cluster_failover.py
  tools/behave_rule.bzl
Labels: priority: medium, type: feature

#180 When testing Grakn, randomize its port and poll to detect its startup
  .bazelrc
  .grabl/automation.yml
  BUILD
  dependencies/graknlabs/artifacts.bzl
  tests/behaviour/background/cluster/environment.py
  tests/behaviour/background/core/environment.py
  tests/behaviour/background/environment_base.py
  tests/behaviour/context.py
  tools/behave_rule.bzl
Labels: priority: high, type: build

#181 Speed up CI
  .grabl/automation.yml
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: bug, type: build

#182 Rename RPC implementation classes for better organisation
  grakn/client.py
  grakn/rpc/cluster/address.py
  grakn/rpc/cluster/database_manager.py
  grakn/rpc/cluster/replica_info.py
  grakn/rpc/cluster/server_address.py
  grakn/rpc/cluster/session.py
  grakn/rpc/database_manager.py
  grakn/rpc/session.py
  tests/integration/test_cluster_failover.py
  tools/behave_rule.bzl
Labels: priority: low, type: refactor

#183 Bind Cluster sessions to single server nodes, and add naive load balancing
  dependencies/graknlabs/artifacts.bzl
  grakn/client.py
  grakn/rpc/cluster/failsafe_task.py
  grakn/rpc/cluster/replica_info.py
  grakn/rpc/cluster/session.py
  requirements.txt
  requirements_dev.txt
  tests/integration/test_cluster_failover.py
Labels: priority: high, type: feature

#185 Raise StopIteration when iterating over an already-completed Stream
  grakn/rpc/stream.py
Labels: priority: high, type: bug

#187 Fix error in test-deployment-pip
  tests/deployment/test.py
Labels: priority: medium, type: build

#188 Fix tests using wrong method to check db existence
  tests/deployment/test.py
  tests/integration/test_cluster_failover.py
  tests/integration/test_concurrent.py
  tools/cluster_test_rule.bzl
Labels: priority: medium, type: bug

#189 Add option to enable inference tracing
  grakn/grakn_proto_builder.py
  grakn/options.py
  requirements.txt
  requirements_dev.txt
Labels: type: feature

#190 Use self-hosted Bazel cache
  .bazelrc
Labels: priority: high, type: build, type: feature

#192 Bump dependencies and VERSION for alpha-8 release
  VERSION
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  requirements.txt
  requirements_dev.txt
  tests/BUILD
Labels: type: build

#191 When closing a client, also close all its sessions
  dependencies/graknlabs/artifacts.bzl
  grakn/client.py
  grakn/rpc/session.py
  grakn/rpc/transaction.py
  tools/behave_rule.bzl
Labels: priority: medium, type: feature

#193 Store more complete cluster address information
  .grabl/automation.yml
  dependencies/graknlabs/artifacts.bzl
  grakn/rpc/cluster/server_address.py
  tests/integration/test_cluster_failover.py
  tools/cluster_test_rule.bzl
Labels: priority: medium, type: feature
