Repository vaticle/typedb-driver-python, pull requests merged in 2021-03, with the labels that each got.

#194 Fix possible ValueError when closing a session
  grakn/rpc/session.py
Labels: priority: medium, type: bug

#198 Fix Cluster failover test intermittently being too slow and failing
  tools/cluster_test_rule.bzl
Labels: priority: high, type: build

#196 Add parallel option
  grakn/grakn_proto_builder.py
  grakn/options.py
  requirements.txt
  requirements_dev.txt
Labels: priority: high, type: feature

#199 Introduce terms: 'internal' and 'external' address
  grakn/client.py
  grakn/rpc/cluster/server_address.py
  tests/integration/test_cluster_failover.py
Labels: priority: medium, type: refactor

#200 Add 'get_type' to local Thing concepts
  .bazelrc
  .grabl/automation.yml
  dependencies/graknlabs/artifacts.bzl
  grakn/concept/proto/concept_proto_builder.py
  grakn/concept/proto/concept_proto_reader.py
  grakn/concept/thing/attribute.py
  grakn/concept/thing/entity.py
  grakn/concept/thing/relation.py
  grakn/concept/thing/thing.py
  grakn/rpc/cluster/failsafe_task.py
  requirements.txt
  requirements_dev.txt
  tests/behaviour/concept/thing/attribute/attribute_steps.py
  tests/behaviour/concept/thing/entity/entity_steps.py
  tests/behaviour/concept/thing/relation/relation_steps.py
  tests/behaviour/concept/thing/thing_steps.py
  tests/behaviour/graql/graql_steps.py
Labels: priority: high, type: feature

#201 Update grakn artifacts
  dependencies/graknlabs/artifacts.bzl
Labels: priority: low, type: build

#203 Upgrade grpcio to 1.36.1, protobuf to 3.15.5
  requirements.txt
  requirements_dev.txt
Labels: priority: medium, type: build

#204 Add prefetch, session, schema lock timeout options
  grakn/options.py
  grakn/options_proto_builder.py
  grakn/query/query_manager.py
  grakn/rpc/session.py
  grakn/rpc/transaction.py
Labels: priority: medium, type: feature

#205 On transaction failover, transfer options to the new session
  grakn/rpc/cluster/session.py
  grakn/rpc/session.py
Labels: priority: medium, type: bug

#210 Fix test-deployment
  README.md
  dependencies/graknlabs/repositories.bzl
  tests/deployment/test.py
Labels: priority: medium, type: bug

#211 Set default parallelism of CoreClient to 2
  grakn/client.py
  grakn/core/client.py
  grakn/core/stream.py
Labels: priority: low, type: feature

#212 Shorten enum names to SessionType, TransactionType
  grakn/api/client.py
  grakn/api/session.py
  grakn/api/transaction.py
  grakn/client.py
  grakn/cluster/client.py
  grakn/cluster/session.py
  grakn/core/client.py
  grakn/core/session.py
  grakn/core/transaction.py
  tests/behaviour/config/parameters.py
  tests/behaviour/connection/session/session_steps.py
  tests/behaviour/connection/transaction/transaction_steps.py
  tests/deployment/test.py
  tests/integration/test_cluster_failover.py
  tests/integration/test_concurrent.py
Labels: priority: high, type: refactor
