Repository vaticle/typedb-driver-python, pull requests merged in 2022-11, with the labels that each got.

#266 Remove calls to `grpc.channel.close()`, which could cause segfaults
  .factory/automation.yml
  .factory/test-cluster.sh
  .factory/test-core.sh
  BUILD
  typedb/connection/cluster/server_client.py
  typedb/connection/core/client.py
  typedb/connection/transaction.py
Labels: type: bug, priority: blocker

#267 Upgrade to 2.12.0
  BUILD
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  requirements.txt
  requirements_dev.txt
  tests/behaviour/background/cluster/environment.py
  tests/behaviour/background/core/environment.py
  tests/behaviour/background/environment_base.py
  tests/behaviour/concept/thing/attribute/attribute_steps.py
  tests/behaviour/concept/thing/entity/entity_steps.py
  tests/behaviour/concept/thing/relation/relation_steps.py
  tests/behaviour/concept/thing/thing_steps.py
  tests/behaviour/concept/type/attributetype/attribute_type_steps.py
  tests/behaviour/concept/type/relationtype/relation_type_steps.py
  tests/behaviour/concept/type/thingtype/thing_type_steps.py
  tests/behaviour/config/parameters.py
  tests/behaviour/connection/database/database_steps.py
  tests/behaviour/connection/session/session_steps.py
  tests/behaviour/connection/transaction/transaction_steps.py
  tests/behaviour/connection/user/user_steps.py
  tests/behaviour/context.py
  tests/behaviour/typeql/typeql_steps.py
  tests/behaviour/util/util_steps.py
  tests/deployment/test.py
  tests/integration/test_cluster_failover.py
  tests/integration/test_typedb.py
  typedb/api/concept/type/role_type.py
  typedb/api/concept/type/thing_type.py
  typedb/api/concept/type/type.py
  typedb/api/query/query_manager.py
  typedb/common/rpc/request_builder.py
  typedb/concept/proto/concept_proto_reader.py
  typedb/concept/type/attribute_type.py
  typedb/concept/type/entity_type.py
  typedb/concept/type/relation_type.py
  typedb/concept/type/role_type.py
  typedb/concept/type/thing_type.py
  typedb/concept/type/type.py
Labels: type: feature, priority: high

#268 Correct python & pyenv instructions for deployment
  .factory/automation.yml
Labels: type: build, priority: blocker
