Repository vaticle/typedb-driver-python, pull requests merged in 2023-05, with the labels that each got.

#293 Support generalised annotations and uniqueness
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  requirements.txt
  tests/behaviour/concept/thing/thing_steps.py
  tests/behaviour/concept/type/attributetype/attribute_type_steps.py
  tests/behaviour/concept/type/thingtype/thing_type_steps.py
  tests/behaviour/config/parameters.py
  tests/behaviour/typeql/typeql_steps.py
  tests/integration/test_stream.py
  typedb/api/concept/thing/thing.py
  typedb/api/concept/type/attribute_type.py
  typedb/api/concept/type/thing_type.py
  typedb/common/exception.py
  typedb/common/rpc/request_builder.py
  typedb/concept/proto/concept_proto_builder.py
  typedb/concept/thing/thing.py
  typedb/concept/type/attribute_type.py
  typedb/concept/type/thing_type.py
Labels: type: feature, priority: high

#295 Fix Factory Badge
  README.md
Labels: type: bug, priority: low

#296 Introduce Values to support expressions
  .factory/automation.yml
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  requirements.txt
  tests/behaviour/concept/thing/attribute/attribute_steps.py
  tests/behaviour/concept/type/attributetype/attribute_type_steps.py
  tests/behaviour/config/parameters.py
  tests/behaviour/typeql/language/expression/BUILD
  tests/behaviour/typeql/typeql_steps.py
  tests/integration/test_typedb.py
  typedb/api/concept/concept.py
  typedb/api/concept/concept_manager.py
  typedb/api/concept/type/attribute_type.py
  typedb/api/concept/type/thing_type.py
  typedb/api/concept/value/value.py
  typedb/common/exception.py
  typedb/common/rpc/request_builder.py
  typedb/concept/concept_manager.py
  typedb/concept/proto/concept_proto_builder.py
  typedb/concept/proto/concept_proto_reader.py
  typedb/concept/type/attribute_type.py
  typedb/concept/type/thing_type.py
  typedb/concept/value/value.py
Labels: type: feature, priority: high

#297 Protocol versioning
  dependencies/vaticle/artifacts.bzl
  requirements.txt
  typedb/common/exception.py
  typedb/common/rpc/request_builder.py
  typedb/common/rpc/stub.py
  typedb/connection/client.py
  typedb/connection/cluster/client.py
  typedb/connection/cluster/server_client.py
  typedb/connection/cluster/stub.py
  typedb/connection/core/client.py
  typedb/connection/core/stub.py
  typedb/stream/request_transmitter.py
Labels: type: feature
