Repository vaticle/typedb-driver-python, pull requests merged in 2023-01, with the labels that each got.

#275 Depend on grpcio<2, protobuf<4
  requirements.txt
  requirements_dev.txt
Labels: type: bug, priority: high

#278 Remove unnecessary delays before closing sessions and clients in tests
  tests/behaviour/background/environment_base.py
Labels: type: refactor, priority: low

#281 Only read TLS CA once
  typedb/connection/cluster/server_client.py
Labels: type: bug, priority: blocker
